---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustermesh-apiserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermesh-apiserver
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnodes
  - ciliumnodes/status
  - ciliumexternalworkloads
  - ciliumexternalworkloads/status
  - ciliumidentities
  - ciliumidentities/status
  - ciliumendpoints
  - ciliumendpoints/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clustermesh-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustermesh-apiserver
subjects:
- kind: ServiceAccount
  name: clustermesh-apiserver
  namespace: kube-system
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: externalworkload-server-certs
  namespace: kube-system
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lVQzkzU3Q3MHg2T1cvQmtaSjJOSjNCb2R3bHAwd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpJd05UQXdXaGNOTWpNeE1ESXdNakl3TlRBd1dqQW9NU1l3SkFZRFZRUURFeDFsZUhSbGNtNWhiSGR2CmNtdHNiMkZrTFdOaExtTnBiR2wxYlM1cGJ6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKbjYKZ1lZbEl5TzBiVmNpc2JPYlB5WjZyaUhuRHc0bEtxa0VsQXhkM3RuUm93TlBnYVRpZUpOdTRHa0NGSUVXZ2lKNApiSXlpRjBMNDFXM0g1M1p6OHk2alFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFECkFRSC9NQjBHQTFVZERnUVdCQlNzdVorWVEzRUNjSHNkZ01tckdrejdMU3o5b1RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpQXp0MUtOekpRSzZLbklxN0IwZVNkdG1nVXRZeEVRSFVKbFZ3bzN3SmRDV1FJaEFNYUd6eDhsN09pcgpSem4rK2dab3ZSbmlxVGFHb3JkR1lDdU1ZUE1kZDJNMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNCakNDQWEyZ0F3SUJBZ0lVSEhnTFNzd2I4T2wxdVVDQVZSVTUrV0UxQ21Vd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpNME56QXdXaGNOTWpNeE1ESXdNak0wTnpBd1dqQXFNU2d3SmdZRFZRUURFeDlqYkhWemRHVnliV1Z6CmFDMWhjR2x6WlhKMlpYSXVZMmxzYVhWdExtbHZNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUUKclpXN3l4SHNtdXcyWkpadnQwNHpXSkFWNlVHU3JMbzQvMEx2Y1RPejl3Ym9zYlVRWHlVbTFHOEREUmRoK2JIRgpJVjJnc3cyTHhPb08wTVpjdThrN0Q2T0JzakNCcnpBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZQdTYKb0lXTGZ2M21qcXJrUHVIN3ROaEtuOWJiTUI4R0ExVWRJd1FZTUJhQUZLeTVuNWhEY1FKd2V4MkF5YXNhVFBzdApMUDJoTURBR0ExVWRFUVFwTUNlQ0gyTnNkWE4wWlhKdFpYTm9MV0Z3YVhObGNuWmxjaTVqYVd4cGRXMHVhVytICkJIOEFBQUV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVy90dXZaNGhzN1F4d09saUNOanJ1ZGhIMGU3T0VTeDgKZ1g3UjMzMlFFQTBDSUI3bG9LWklNdmJWYjNQY1FGZnZYd25JY3Z4dFUxeWRYamt2K3hGU0pHblAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVAwNmF4VTFLdU1QbUtxSllMYmVFalpZbk5Fa3MwNTM2MEExaDJvbmc4SDFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFclpXN3l4SHNtdXcyWkpadnQwNHpXSkFWNlVHU3JMbzQvMEx2Y1RPejl3Ym9zYlVRWHlVbQoxRzhERFJkaCtiSEZJVjJnc3cyTHhPb08wTVpjdThrN0R3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: externalworkload-admin-certs
  namespace: kube-system
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lVQzkzU3Q3MHg2T1cvQmtaSjJOSjNCb2R3bHAwd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpJd05UQXdXaGNOTWpNeE1ESXdNakl3TlRBd1dqQW9NU1l3SkFZRFZRUURFeDFsZUhSbGNtNWhiSGR2CmNtdHNiMkZrTFdOaExtTnBiR2wxYlM1cGJ6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKbjYKZ1lZbEl5TzBiVmNpc2JPYlB5WjZyaUhuRHc0bEtxa0VsQXhkM3RuUm93TlBnYVRpZUpOdTRHa0NGSUVXZ2lKNApiSXlpRjBMNDFXM0g1M1p6OHk2alFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFECkFRSC9NQjBHQTFVZERnUVdCQlNzdVorWVEzRUNjSHNkZ01tckdrejdMU3o5b1RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpQXp0MUtOekpRSzZLbklxN0IwZVNkdG1nVXRZeEVRSFVKbFZ3bzN3SmRDV1FJaEFNYUd6eDhsN09pcgpSem4rK2dab3ZSbmlxVGFHb3JkR1lDdU1ZUE1kZDJNMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIwVENDQVhhZ0F3SUJBZ0lVWHZKOHl0M0ZqWlkvVmFlaGRoOWRzbjlwb2Jrd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpNME56QXdXaGNOTWpNeE1ESXdNak0wTnpBd1dqQVBNUTB3Q3dZRFZRUURFd1J5YjI5ME1Ga3dFd1lICktvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVPRWxrTHVsbUxXR3RQVTRmd2xIRktlYi9zTnUwelZ3OXZJN1UKaFZSOWthdHdDYzlCaEVnQkNTOGhpQ01NaEFGQytXaE9ZVzdFVEZSRjRVc1FZeFF1UmFPQmxqQ0JrekFPQmdOVgpIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkCkV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZNM1h1VWV0UEw1K2xOUmd0dXRLeVRJRkQrZFFNQjhHQTFVZEl3UVkKTUJhQUZLeTVuNWhEY1FKd2V4MkF5YXNhVFBzdExQMmhNQlFHQTFVZEVRUU5NQXVDQ1d4dlkyRnNhRzl6ZERBSwpCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUF2TFdRWUI4UyszUk9sVXNtaENYb29CbzV4YVJMUGo2M0FDTU1kTUhTCnd5RUNJUUNWMldSNllWMWQ4RThOdkQxNFZNNFgra2dET3hrN2xYYnhKalFRUGZkRGxRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5mci9BbWkwUWE1LzVtNVdaMEtsL3UyYm1GUHhHTmFhV3ovZFMwSExydzZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFT0Vsa0x1bG1MV0d0UFU0ZndsSEZLZWIvc051MHpWdzl2STdVaFZSOWthdHdDYzlCaEVnQgpDUzhoaUNNTWhBRkMrV2hPWVc3RVRGUkY0VXNRWXhRdVJRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: externalworkload-client-certs
  namespace: kube-system
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lVQzkzU3Q3MHg2T1cvQmtaSjJOSjNCb2R3bHAwd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpJd05UQXdXaGNOTWpNeE1ESXdNakl3TlRBd1dqQW9NU1l3SkFZRFZRUURFeDFsZUhSbGNtNWhiSGR2CmNtdHNiMkZrTFdOaExtTnBiR2wxYlM1cGJ6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKbjYKZ1lZbEl5TzBiVmNpc2JPYlB5WjZyaUhuRHc0bEtxa0VsQXhkM3RuUm93TlBnYVRpZUpOdTRHa0NGSUVXZ2lKNApiSXlpRjBMNDFXM0g1M1p6OHk2alFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFECkFRSC9NQjBHQTFVZERnUVdCQlNzdVorWVEzRUNjSHNkZ01tckdrejdMU3o5b1RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpQXp0MUtOekpRSzZLbklxN0IwZVNkdG1nVXRZeEVRSFVKbFZ3bzN3SmRDV1FJaEFNYUd6eDhsN09pcgpSem4rK2dab3ZSbmlxVGFHb3JkR1lDdU1ZUE1kZDJNMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI0ekNDQVltZ0F3SUJBZ0lVYzZaZG4zUHpUTmYrQTdpR0JVWmkzOUhDM3hRd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpNME56QXdXaGNOTWpNeE1ESXdNak0wTnpBd1dqQWJNUmt3RndZRFZRUURFeEJsZUhSbGNtNWhiSGR2CmNtdHNiMkZrTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWG5wYzdhQXpJazcrN1pyaE1EaEsKSjlHMEVmOUJVTndQL1NCTjBXcUVLRDR4Q2M1UktpY3p2Qmc2VnJGZng2VldwNnBvSjI1Nk94d3pMNFk1RDN2Lwo0S09CblRDQm1qQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHCkFRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGR2Z1S3lTVlB5YTBZRDRMdHVIL2VtVGMKOVJ5ZU1COEdBMVVkSXdRWU1CYUFGS3k1bjVoRGNRSndleDJBeWFzYVRQc3RMUDJoTUJzR0ExVWRFUVFVTUJLQwpFR1Y0ZEdWeWJtRnNkMjl5YTJ4dllXUXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSWZReFJnSTdJRkp1a1RCCks3VXZiRExud3NvTG5xZysxRXFqZ1I0c3RKL1ZBaUJQL1ZJSUJhZUNVcS9ENEYxWi9iQmVZUTMzVUxnYXhVdkcKNVAzS200WjhMUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUNubTFKZFVIV09LQUluTVNyV0s3eVorZ1lxOWlGTW1jNFcvSXM1NE9LVTdvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWG5wYzdhQXpJazcrN1pyaE1EaEtKOUcwRWY5QlVOd1AvU0JOMFdxRUtENHhDYzVSS2ljegp2Qmc2VnJGZng2VldwNnBvSjI1Nk94d3pMNFk1RDN2LzRBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: externalworkload-ca-cert
  namespace: kube-system
binaryData:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lVQzkzU3Q3MHg2T1cvQmtaSjJOSjNCb2R3bHAwd0NnWUlLb1pJemowRUF3SXcKS0RFbU1DUUdBMVVFQXhNZFpYaDBaWEp1WVd4M2IzSnJiRzloWkMxallTNWphV3hwZFcwdWFXOHdIaGNOTWpBeApNREl3TWpJd05UQXdXaGNOTWpNeE1ESXdNakl3TlRBd1dqQW9NU1l3SkFZRFZRUURFeDFsZUhSbGNtNWhiSGR2CmNtdHNiMkZrTFdOaExtTnBiR2wxYlM1cGJ6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKbjYKZ1lZbEl5TzBiVmNpc2JPYlB5WjZyaUhuRHc0bEtxa0VsQXhkM3RuUm93TlBnYVRpZUpOdTRHa0NGSUVXZ2lKNApiSXlpRjBMNDFXM0g1M1p6OHk2alFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFECkFRSC9NQjBHQTFVZERnUVdCQlNzdVorWVEzRUNjSHNkZ01tckdrejdMU3o5b1RBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpQXp0MUtOekpRSzZLbklxN0IwZVNkdG1nVXRZeEVRSFVKbFZ3bzN3SmRDV1FJaEFNYUd6eDhsN09pcgpSem4rK2dab3ZSbmlxVGFHb3JkR1lDdU1ZUE1kZDJNMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ca.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVaQlFyVGVYZ1VVYUo3NVlsNWhzNW9RTlcxbnlLc0hrUGw0QzBIRDlMK01vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbWZxQmhpVWpJN1J0VnlLeHM1cy9KbnF1SWVjUERpVXFxUVNVREYzZTJkR2pBMCtCcE9KNAprMjdnYVFJVWdSYUNJbmhzaktJWFF2alZiY2ZuZG5QekxnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
